In [39]:
#y = 3x1 + 2x2 + noise
import numpy as np
np.random.seed(42)

In [40]:
no_of_samples = 1000
X = np.random.rand(no_of_samples,2)
X

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       ...,
       [0.75137509, 0.65695516],
       [0.95661462, 0.06895802],
       [0.05705472, 0.28218707]])

In [41]:
true_weights = np.array([3,2])
noise = np.random.rand(1)
true_weights,noise

(array([3, 2]), array([0.26170568]))

In [42]:
yhat = np.dot(X,true_weights.T) + noise
yhat

array([3.28675465, 3.65500448, 1.04175065, 2.16830881, 3.48119587,
       2.26327887, 3.18371183, 1.17398961, 2.22394528, 2.13999902,
       2.37625209, 1.87086332, 3.20026756, 1.88919591, 2.13185022,
       2.42538849, 2.35463154, 4.77539648, 1.37089122, 3.19470975,
       1.61817421, 2.18351205, 2.3630902 , 2.23697495, 2.27154543,
       4.72072521, 4.86985721, 3.89915409, 0.91914891, 1.04804821,
       1.97043562, 3.46142486, 2.18990138, 2.28887232, 2.45913149,
       2.97587135, 1.90919489, 3.84029205, 2.72360603, 1.56884099,
       4.09761222, 1.38151646, 1.84501929, 3.72563916, 3.86777376,
       2.046978  , 3.66661522, 3.56219842, 2.68498621, 0.55374592,
       1.62881406, 2.22191501, 3.48298956, 3.00395673, 1.10206   ,
       1.45340262, 4.6670394 , 3.90483813, 3.04586203, 4.01806716,
       4.47620875, 1.43581996, 1.79972675, 4.43721115, 1.30405668,
       1.95815431, 1.29653213, 3.73684066, 3.22411547, 3.29615866,
       3.65261216, 2.35520782, 1.19000106, 3.09575673, 0.97343

In [43]:
epochs = 1000
alpha = 0.01
weights = np.random.randn(2)
bias = np.random.randn(1)
weights,bias

(array([ 0.35502245, -0.2211131 ]), array([-0.84028143]))

In [44]:
for _ in range(epochs):
    ypred = np.dot(X,weights) + bias
    error = ypred - yhat

    dw = (2/no_of_samples) * np.dot(X.T,error)
    dbias = (2/no_of_samples) * np.sum(error)

    weights-=alpha*dw
    bias-=alpha*dbias

    if(_%100==0):
        print("Loss : ", np.mean(np.abs(error)))

Loss :  3.5242882873512524
Loss :  0.3963201855043319
Loss :  0.3319260973994992
Loss :  0.2947840361669756
Loss :  0.2621060850182321
Loss :  0.23320032742301702
Loss :  0.20759620883637386
Loss :  0.1848885236017489
Loss :  0.16474499039874502
Loss :  0.14684627687435392
