## Krishna Manoj PVR

## 22BD1A051F

In [38]:
import tensorflow as tf

In [39]:
arr1 = tf.constant([[[1, 2, 3],[4, 5, 6]],
                    [[6, 7, 8], [9, 10, 11]]])

arr2 = tf.constant([[[1, 2, 5],[8, 9, 10]],
                    [[10, 8, 7], [9, 10, 11]]])

In [40]:
# Perform element-wise addition, subtraction, multiplication, division, and power operations
print("Addition of two tensors:")
tf.print(tf.add(arr1, arr2))

print("Subtraction of two tensors:")
tf.print(tf.subtract(arr1, arr2))

Addition of two tensors:
[[[2 4 8]
  [12 14 16]]

 [[16 15 15]
  [18 20 22]]]
Subtraction of two tensors:
[[[0 0 -2]
  [-4 -4 -4]]

 [[-4 -1 1]
  [0 0 0]]]


In [41]:
print("Multiplication of two tensors:")
tf.print(tf.multiply(arr1, arr2))

print("Division of two tensors:")
tf.print(tf.divide(arr1, arr2))

Multiplication of two tensors:
[[[1 4 15]
  [32 45 60]]

 [[60 56 56]
  [81 100 121]]]
Division of two tensors:
[[[1 1 0.6]
  [0.5 0.55555555555555558 0.6]]

 [[0.6 0.875 1.1428571428571428]
  [1 1 1]]]


In [42]:
print("Exponential of arr1:")
tf.print(tf.exp(tf.cast((arr1), dtype=tf.float32)))

print("Logarithm of arr1:")
tf.print(tf.math.log(tf.cast((arr1), dtype=tf.float32)))


Exponential of arr1:
[[[2.71828175 7.38905621 20.085537]
  [54.5981483 148.413162 403.428772]]

 [[403.428772 1096.63318 2980.95801]
  [8103.08398 22026.4648 59874.1406]]]
Logarithm of arr1:
[[[0 0.693147182 1.09861231]
  [1.38629436 1.60943794 1.79175949]]

 [[1.79175949 1.94591022 2.07944155]
  [2.19722462 2.30258512 2.39789534]]]
