## Krishna Manoj PVR
## 22BD1A051F

In [43]:
import tensorflow as tf

In [44]:
t1 = tf.constant([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

t2 = tf.constant([
    [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]],
    [[37, 38, 39, 40], [41, 42, 43, 44], [45, 46, 47, 48]]
])


In [45]:
#merging
c1 = tf.concat([t1,t2],axis=0)
c1

<tf.Tensor: shape=(4, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])>

In [46]:
c2 = tf.concat([t1,t2],axis=1)
c2


<tf.Tensor: shape=(2, 6, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])>

In [47]:
c3 = tf.concat([t1,t2],axis=2)
c3

<tf.Tensor: shape=(2, 3, 8), dtype=int32, numpy=
array([[[ 1,  2,  3,  4, 25, 26, 27, 28],
        [ 5,  6,  7,  8, 29, 30, 31, 32],
        [ 9, 10, 11, 12, 33, 34, 35, 36]],

       [[13, 14, 15, 16, 37, 38, 39, 40],
        [17, 18, 19, 20, 41, 42, 43, 44],
        [21, 22, 23, 24, 45, 46, 47, 48]]])>

In [48]:
#splitting
a,b = tf.split(c1,num_or_size_splits=2,axis = 0)
a,b

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],
 
        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]])>)

a,b = tf.split(c1,num_or_size_splits=2,axis = 0)
a,b

In [49]:
#non-uniform split
n1,n2,n3 = tf.split(c3,num_or_size_splits=[2,1,5],axis=2)
n1,n2,n3


(<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],
 
        [[13, 14],
         [17, 18],
         [21, 22]]])>,
 <tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
 array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]]])>,
 <tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
 array([[[ 4, 25, 26, 27, 28],
         [ 8, 29, 30, 31, 32],
         [12, 33, 34, 35, 36]],
 
        [[16, 37, 38, 39, 40],
         [20, 41, 42, 43, 44],
         [24, 45, 46, 47, 48]]])>)